Microsoft Teams plugin for auto
intuit/auto pull request #1570
Opened 2020-10-07 08:21 UTC by mukul13

# What Changed

Microsoft Teams plugin for auto

## Why
Microsoft teams also support incoming webhook flow. This plugin is to integrate auto with microsoft team's webhook flow

Todo:

- [x ] Add tests
- [ ] Add docs

## Change Type

Indicate the type of change your pull request is:

- [ x] `documentation`
- [ ] `patch`
- [ x] `minor`
- [ ] `major`

2020-10-08 16:51 UTC, hipstersmoothie requested changes
A few changes. I also pushed some commits to make this plugin extend from the slack plugin. If you could test this out it would be awesome!

2020-10-12 13:20 UTC, mukul13 commented on .gitignore
> +.intuitgithookrc
got it. will do!

2020-10-12 13:23 UTC, mukul13 commented on plugins/microsoft-teams/src/index.ts
> +import { githubToSlack } from "@atomist/slack-messages";
yes, it still works but I think there can be some differences in few text transformations (for example, emojis etc) between slack and Microsoft teams. It looks something like below currently
<img width="716" alt="Screenshot 2020-10-12 at 6 51 19 PM" src="https://user-images.githubusercontent.com/8403230/95751355-22abc700-0cbc-11eb-8106-767c2f81403e.png">

2020-10-12 13:24 UTC, mukul13 commented
will test the functionality out today in ms teams and add an update here. Apologies for the delay!

2020-10-15 17:04 UTC, mukul13 commented
@hipstersmoothie : it's working as expected with microsoft teams too currently.
a caveat: Due to recent changes, SLACK_WEBHOOK_URL variable is being used in .env for Microsoft teams instead of MICROSOFT_TEAMS_WEBHOOK_URL. Is that okay or will it be confusing?

2020-10-21 23:17 UTC, hipstersmoothie commented
@mukul13 Good catch! I changed the code so it will now uses `MICROSOFT_TEAMS_WEBHOOK_URL`

2020-10-21 23:18 UTC, hipstersmoothie commented
@mukul13 seems like I can't push to your fork anymore. mind giving me access?

2020-10-27 18:09 UTC, hipstersmoothie approved these changes

2020-10-27 18:09 UTC, merged

2020-10-27 18:24 UTC, adierkens commented
<!-- GITHUB_RELEASE COMMENT: released -->
:rocket: PR was released in [`v9.61.0`](https://github.com/intuit/auto/releases/tag/v9.61.0) :rocket: