Prefer project npmrc if present
intuit/auto pull request #1818
Opened 2021-02-20 23:20 UTC by zephraph

# What Changed

`.npmrc` files now prefer the project directory over the home directory. If there's no `.npmrc` in the project directory, but there _is_ in the home directory, it'll fall back to use that one.

## Why

Often when someone writes a `.npmrc` from CI, they just write it in place. That's valid to npm, but not recognized by auto. If a user writes a local .npmrc file, that'll be preferred over the global one (in the home directory). This could lead to situations where the `.npmrc` file gets written by auto, but _doesn't_ get used by the project. 

Todo:

- [x] Add tests
- [x] Add docs

## Change Type

Indicate the type of change your pull request is:

- [ ] `documentation`
- [ ] `patch`
- [x] `minor`
- [ ] `major`

2021-02-20 23:22 UTC, zephraph commented
Welp, found my first bug?

```
?? packages/cli/.npmrc
Error: Working directory is not clean, make sure all files are committed
```

Looks like `process.cwd()` is _not_ the right way to go here...

2021-02-21 01:39 UTC, hipstersmoothie commented on plugins/npm/src/set-npm-token.ts
> +    logger.verbose.info(`${npmrcFilePath} doesn't exist or cannot be read`);
could add the error using logger.veryVerbose.error(error)

2021-02-21 01:43 UTC, hipstersmoothie commented on plugins/npm/src/utils.ts
> +export const isMonorepo = (): boolean => !!getLernaPathIfExists();
```suggestion
export const isMonorepo = (): boolean => Boolean(getLernaPathIfExists());
```

2021-02-21 01:43 UTC, hipstersmoothie requested changes
Looks good, just a few changes

2021-02-21 19:13 UTC, hipstersmoothie approved these changes

2021-02-22 17:29 UTC, hipstersmoothie commented
@zephraph could you fix the failing test?

2021-02-24 04:52 UTC, zephraph commented
🤞

2021-06-03 20:29 UTC, zephraph commented
I haven't touched this in a while. I might revisit one day, but I'm going to close this for today.

2021-06-03 20:29 UTC, closed without merging